name: Eggplant Runner Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Run-Test-Configuration:
    runs-on: ubuntu-latest
    name: Run Test Configuration
    steps:
      - name: Eggplant Runner 1
        uses: keysight-eggplant/eggplant-github-action@v1.0.8
        with:
          dryRun: false
          serverURL: "https://eval.us.dai.eggplant.cloud/"
          clientID: "client:dai:api:integration:938be7ed-220e-4eb2-b012-2a0a779573d0"
          testConfigID: "952bee5b-c626-4fa7-9460-e7a6c9172cfb" # Test configuration which need to perform execution
          clientSecret: "Z3t1cQNtPBFI7je68XtII81K1qI3csoM" # Eggplant DAI service client secret
          # Alternatively, DAI client secret can be set as repo secret
          # byy goingg to GitHub Settings > Secrets > Actions
          # clientSecret: "${{secrets.DAI_CLIENT_SECRET}}
